name: navbar_router
description: A flutter package to build advanced bottomnavbar with minimal code and hassle

version: 0.4.1
homepage: https://github.com/maheshmnj/navbar_router
repository: https://github.com/maheshmnj/navbar_router
issue_tracker: https://github.com/maheshmnj/navbar_router/issues

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  cached_network_image: ^3.2.3
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.0
  retry: ^3.1.0
  timeago: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
